[tool.pytest.ini_options]
addopts = "-s -v"
minversion = "6.0"
testpaths = [
  "v5",
  "v6"
]
log_cli = 1
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
